### ISSUE TITLE
Messages bleed into each other on narrower windows

### ISSUE THREAD

**Issue by knubie** [urbit/talk#17]
This is due to the `.gram` elements having a set height, which I know is required for the react-infinite plugin. Not sure what the best way to handle this is, maybe somehow retrieve their natural height before passing in to `Infinite`? But then how do you deal with window resizing, check and rerender on resize event?
![screen shot 2016-06-11 at 2 50 43 pm](https://cloud.githubusercontent.com/assets/431251/15986922/657d2542-2fe4-11e6-8468-94ce289d76ff.png)

**Comment by galenwp** [comment]
Oof!  That's a good one.  I was just thinking that I needed to test talk on smaller windows again.

The desired behavior is definitely just to have lines wrap naturally.  But I can't think of the right way to do it off the top of my head.  What you suggest could work (create an element offscreen and measure the height), and resizing the window could trigger a re-render.  I imagine there would probably be some complexity related to scrolling though.

**Comment by galenwp** [comment]
Another thing that comes to mind is just forcing long lines to stay long.  That is, you'd have to scroll right a bit to read the whole line.  This could be an easy (albeit sorta ugly) interim fix.

**Comment by knubie** [comment]
I was thinking about that too, re: forcing long lines to stay long. A simple `white-space: nowrap` on `.speech` should do the trick. But yeah, would definitely want to think of a better long-term solution.

**Comment by galenwp** [comment]
As an aside: I think this is probably one of my most-hated problems with the web.  Not being able to determine the width of type before it gets rendered is _so annoying_.

**Comment by knubie** [comment]
Some related discussion at seatgeek/react-infinite#61. Seems you can pass in a max height instead of the exact height and it will still work, albeit less efficiently. I.e. `MESSAGE_HEIGHT_SAME = 81` which would be worst-case scenario of a message wrapping to 3 lines (27 \* 3).

Another option might be to pass in the max-height/worst-case heights on initial render, then grab the actual heights and re-render. But seems like then you would need to render twice for each incoming message. Might not be worth it.

**Comment by knubie** [comment]
Might be better to switch to something like [react-chatview](https://github.com/dustingetz/react-chatview) or [react-infinite-any-height](https://github.com/Radivarig/react-infinite-any-height). There doesn't really seem to be a reliable way to do this in react-infinite.

**Comment by galenwp** [comment]
Hm.  The latter looks like less of a modification of react-infinite.  Tough to tell which one is more mature.

**Comment by ohAitch** [comment]
react-chatview:
- Not actually infinite - currently all elements that have been loaded
  remain the dom

**Comment by galenwp** [comment]
Heh, okay.  The latter is probably better.
