### ISSUE TITLE
No 'offline' indication

### ISSUE THREAD

**Issue by knubie** [urbit/talk#21]
The interface gives no indication when it's been disconnected, the 'offline' class never gets added to the body.

**Comment by knubie** [comment]
Correction: the offline class does get added, but there's no styling.

**Comment by knubie** [comment]
Correction correction: It does fail to detect offline (seems to work when setting throttling to 'offline' in chrome, but not when the computer is actually offline).

The `urb.poll` xhr request never returns when offline, so `urb.poll.dely` never changes.

**Comment by galenwp** [comment]
Yeah, I've always wanted this to work.  @ohAitch did the initial implementation.  Want to weigh in?

**Comment by knubie** [comment]
I think I have a solution, actually. Setting a `timeout` property on the xhr object, and an `ontimeout` handler seems to work. The timeout is set to 60s.

**Comment by galenwp** [comment]
That makes sense to me.  Will that work if you get reconnected?

**Comment by knubie** [comment]
Testing it out now, it only removes 'offline' when a new message comes in. Something to do with `params.dely` not being set? I've got to head out soon, but I'll keep poking around with it when I get back.

**Comment by ohAitch** [comment]
I'd use the heartbeat for offline detection, if you haven't gotten one for a couple minutes then something's up with the long poll. Not sure where precisely to hook this into `urb.js`, an urb.poll.lastSeen `Date` perhaps?

**Comment by ohAitch** [comment]
(or something more fancy with onDisconnect/onReconnect handlers)
