### ISSUE TITLE
Error: [%ap-abut-bad-bone %talk 256]

### ISSUE THREAD

**Issue by livweb-havweb** [urbit/talk#34]
Been getting this for about a week -- pops up iteratively in the middle of my Talk feed:

```
[%ap-abut-bad-bone %talk 256] 
```

But it seems like everything still works fine. I can see and send messages from both the CLI and the browser UI.

What's up?

**Comment by galenwp** [comment]
This is almost definitely an issue with `arvo`.  This repo is just the frontend `talk` code.

**Comment by livweb-havweb** [comment]
Yeah whoops. I'll move it.
