### ISSUE TITLE
[minor] Page scrolls when someone talks

### ISSUE THREAD

**Issue by juped** [urbit/talk#5]
If you're scrolled up from the bottom at all, the position will still move when someone says something new, making it a pain to read backlog.

(I don't know if this is what was on Anton's older branches - I put those under @galenwp just in case they had something useful, since they didn't look identical to the stuff here)

**Comment by galenwp** [comment]
I've actually worked on this problem, and it should be fixed.  Will look into it.

**Comment by galenwp** [comment]
After some investigation — the backlog jumps by one message height — so it's not nearly as bad as it used to be.  (I thought you were referencing the previous behavior when it would scroll you back to the bottom.)  Can fix this.
